# This file was generated by GoReleaser. DO NOT EDIT.
cask "fulcrum" do
  postflight_steps do
    on_macos do
      # The binary is not notarised, so Gatekeeper quarantines anything
      # downloaded from the internet and the first run dies with "cannot
      # be opened because the developer cannot be verified" — which reads
      # like a broken install rather than a policy.
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/fulcrum"]
    end
  end

  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "6b67d20b140759091d91237ce167d4654551d6465c2b1e9e5d3b8a2b8d655d70"
      url "https://github.com/headwayio/fulcrum-cli/releases/download/v#{version}/fulcrum_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9a30466b2c69215989a04e6750d0c024d0195747708acf870d642c2695a52b0a"
      url "https://github.com/headwayio/fulcrum-cli/releases/download/v#{version}/fulcrum_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "afe06d47191e78b24cd010d48f23efe5f2168e87c1c93fdec1cfca6acd08eedc"
      url "https://github.com/headwayio/fulcrum-cli/releases/download/v#{version}/fulcrum_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "cdc67bd014f0fc57fa7a5f60ff91796b306b767d805d38111f1575256a5a50f1"
      url "https://github.com/headwayio/fulcrum-cli/releases/download/v#{version}/fulcrum_Linux_x86_64.tar.gz"
    end
  end

  name "fulcrum"
  desc "Fulcrum from your terminal, and for the coding harness you work in"
  homepage "https://github.com/headwayio/fulcrum-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fulcrum"

  # No zap stanza required
end
