# This file was generated by GoReleaser. DO NOT EDIT.
cask "fulcrum" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "7cce2748cbedf2a78a7fa8b91de51bb022dc7287445c062d1d0413d2b568bd30"
      url "https://github.com/headwayio/fulcrum-cli/releases/download/v#{version}/fulcrum_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "5ea681f832fbbb811c212e69d0795ea0735655d98c6ba6d610065330a838016e"
      url "https://github.com/headwayio/fulcrum-cli/releases/download/v#{version}/fulcrum_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6eb74c317ad6ae26c90a0f7add9bcc9d07547b9cd1a43e040c2608a7d5b3988f"
      url "https://github.com/headwayio/fulcrum-cli/releases/download/v#{version}/fulcrum_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "7f5423835bccc94b58ce6c9d13a0aa2338c0237cf11b093b3797214b41af6600"
      url "https://github.com/headwayio/fulcrum-cli/releases/download/v#{version}/fulcrum_Linux_arm64.tar.gz"
    end
  end

  name "fulcrum"
  desc "Fulcrum from your terminal, and for the coding harness you work in"
  homepage "https://github.com/headwayio/fulcrum-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fulcrum"

  postflight do
    if OS.mac?
      # The binary is not notarised, so Gatekeeper quarantines anything
      # downloaded from the internet and the first run dies with "cannot
      # be opened because the developer cannot be verified" — which reads
      # like a broken install rather than a policy.
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/fulcrum"]
    end
  end

  # No zap stanza required

end
